### ISSUE TITLE
[feat] 식당 검증 로직 추가

### ISSUE THREAD

**Issue by kgy1008** [Team-Hankki/hankki-server#144]
## Issue 📌
식당 제보 시 3가지 경우의 수에 따른 분기처리 추가

## Todo ✔️
- [x] 식당 중복 검증 시, 소수(위경도) 비교와 문자열(도로명 주소) 비교 중 무엇이 성능이 좋은지 찾기
- [x] 나의 대학교에는 등록이 되어 있지 않지만 타 대학교에 등록이 되어 있는 경우와 나의 대학교에 등록이 되어 있는 경우 분기 처리
- [x] api 명세서 수정
