### ISSUE TITLE
[fix] 기본이미지 정책 변경에 대한 로직 수정

### ISSUE THREAD

**Issue by Parkjyun** [Team-Hankki/hankki-server#156]
## Issue 📌
- 기본 이미지를 클라이언트에서 관리하기로 했습니다.
- 이에 식당 등록시 storeImage를 생성하지 않습니다.
- 식당세부 조회시 기본이미지라면 빈리스트를 반환합니다(로직 수정 X)
- 식당 리스트 조회시 저장된 storeimage가 없다면(기본이미지라면) imageUrl로 null을 보내줘야 합니다.
- 식당 썸네일 조회시 저장된 storeimage가 없다면(기본이미지라면) imageUrl로 null을 보내줘야 합니다. 
## Todo ✔️
- [x] 식당등록시 이미지가 안들어왔다면 storeimage저장 안 하도록 수정
- [ ] 식당 리스트 조회 로직 변경
- [x] 식당 썸네일 로직 조회 변경
