### ISSUE TITLE
[feat] 족보 공유 관련 API 경로 비로그인 유저도 접근할 수 있게 열기

### ISSUE THREAD

**Issue by PicturePark1101** [Team-Hankki/hankki-server#232]
## Issue 📌

족보 공유 관련 API 경로 비로그인 유저도 접근할 수 있게 열기
족보 상세보기 API 공유용 따로 분리

## Todo ✔️
- [ ] 로직 재체크하기
- [ ] 족보 상세보기 API
- [ ] 족보 주인인지 판별 API
- [ ] 족보 주인 닉네임 API
