### ISSUE TITLE
[feat] 사용자 대학교 설정 정보 조회 및 변경 api 생성

### ISSUE THREAD

**Issue by Parkjyun** [Team-Hankki/hankki-server#37]
## Issue 📌
사용자의 대학교 설정정보를 조회 및 변경하는 api입니다.
redis를 사용하여 해당 정보를 저장합니다.
## Todo ✔️
- [ ] redis 의존성 설정 및 연결
- [ ] 대학교 설정 정보 조회 api 생성
- [ ] 대학교 설정 정보 변경 api 생성
